//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entity_Framework_Working_Example
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeTable
    {
        public int PersonId { get; set; }
        public string PersonFirstName { get; set; }
        public string PersonLastName { get; set; }
        public int PersonAge { get; set; }
        public string PersonAddress { get; set; }
        public string PersonNumber { get; set; }
        public string PersonEmailAddress { get; set; }
        public string EmploymentTitle { get; set; }
    }
}
